table FactAprovacao
	lineageTag: 9400547a-0c9b-4a52-9697-4756e9620a48

	column _aprovador
		dataType: string
		lineageTag: 0d20ee36-fcc6-4824-900b-ee1a51f13add
		summarizeBy: none
		sourceColumn: _aprovador

		annotation SummarizationSetBy = Automatic

	column OrderServiceCode
		dataType: string
		lineageTag: 4888a799-0071-4fde-b13b-9a12e3c35877
		summarizeBy: none
		sourceColumn: OrderServiceCode

		annotation SummarizationSetBy = Automatic

	column valor_orcado
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 39fc8cb8-e28c-4bfe-aea9-d0f00093b366
		summarizeBy: sum
		sourceColumn: valor_orcado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column _valor_aprovado
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: dafa7c49-08df-40b9-8e41-1458f6e8acd1
		summarizeBy: sum
		sourceColumn: _valor_aprovado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column data_aprovacao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 65fd3bff-485f-4625-a020-9e2b791b7d5e
		summarizeBy: none
		sourceColumn: data_aprovacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _tipo_manutencao
		dataType: string
		lineageTag: d06dfa79-1f7f-4996-933c-52a6f4b88222
		summarizeBy: none
		sourceColumn: _tipo_manutencao

		annotation SummarizationSetBy = Automatic

	column _faixa_qtde_itens
		dataType: string
		lineageTag: bd68c17b-3b4f-44f9-910b-3f107881dae9
		summarizeBy: none
		sourceColumn: _faixa_qtde_itens

		annotation SummarizationSetBy = Automatic

	column _monta
		dataType: string
		lineageTag: 076e71b3-feac-4f09-bf04-2504b08b8cf0
		summarizeBy: none
		sourceColumn: _monta

		annotation SummarizationSetBy = Automatic

	column total_int_rev
		dataType: int64
		formatString: 0
		lineageTag: 5a48e1be-7abb-483a-9bd5-947fb1670901
		summarizeBy: sum
		sourceColumn: total_int_rev

		annotation SummarizationSetBy = Automatic

	column total_int_cot
		dataType: int64
		formatString: 0
		lineageTag: 87466b47-d1d3-4cee-b1f0-d97bb84e20b4
		summarizeBy: sum
		sourceColumn: total_int_cot

		annotation SummarizationSetBy = Automatic

	column peso_os
		dataType: double
		lineageTag: 24bffba2-e18b-4c61-b6b4-2246eee3aeb0
		summarizeBy: sum
		sourceColumn: peso_os

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sla_aprovocao
		dataType: double
		formatString: 0.00
		lineageTag: 6d083576-f0ad-4958-bb39-aa1a4b6587ab
		summarizeBy: average
		sourceColumn: sla_aprovocao

		annotation SummarizationSetBy = User

	column _data_sla1
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4538fdb-1c39-49eb-9399-867a356fb9c0
		summarizeBy: none
		sourceColumn: _data_sla1

		variation Variation
			isDefault
			relationship: 7221068d-edc9-4469-a496-d827082a408d
			defaultHierarchy: LocalDateTable_8c0957e4-68f4-44b5-9cd7-1ff1789ff0e0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _data_sla2
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9572f6a8-4da5-49b6-99b5-9928bd0f5cb1
		summarizeBy: none
		sourceColumn: _data_sla2

		variation Variation
			isDefault
			relationship: 4ea1cd20-46a2-43d4-8b85-c7d235e03d06
			defaultHierarchy: LocalDateTable_c7085e68-dc3a-437c-87f0-d258848a2011.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column familia_do_modelo
		dataType: string
		lineageTag: 398a9fcb-19a2-4038-919c-a71d3224bf24
		summarizeBy: none
		sourceColumn: familia_do_modelo

		annotation SummarizationSetBy = Automatic

	column StatusTypeDescription
		dataType: string
		lineageTag: 62cee118-6005-448f-94ec-c66f8eedfcc9
		summarizeBy: none
		sourceColumn: StatusTypeDescription

		annotation SummarizationSetBy = Automatic

	column YearWeek
		dataType: int64
		formatString: 0
		lineageTag: 122139ad-e79f-4c9f-82d8-aad46c3fbc08
		summarizeBy: sum
		sourceColumn: YearWeek

		annotation SummarizationSetBy = Automatic

	column soma_peso_os_semana_aprovador
		dataType: double
		lineageTag: b27de3c3-e4db-40c5-a30b-2af2bdda3339
		summarizeBy: sum
		sourceColumn: soma_peso_os_semana_aprovador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_dias_uteis_semana
		dataType: int64
		formatString: 0
		lineageTag: 22e41486-a432-4ee7-9ac2-206f6fb198c3
		summarizeBy: sum
		sourceColumn: total_dias_uteis_semana

		annotation SummarizationSetBy = Automatic

	column produtividade_semana_aprovador
		dataType: double
		lineageTag: 854dbf81-0789-4cda-b90d-4e725d026c16
		summarizeBy: sum
		sourceColumn: produtividade_semana_aprovador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_os_semana_aprovador
		dataType: int64
		formatString: 0
		lineageTag: 635a347e-a2d7-435c-b43f-92a720f74ef3
		summarizeBy: sum
		sourceColumn: total_os_semana_aprovador

		annotation SummarizationSetBy = Automatic

	column media_diaria_os_aprovador
		dataType: double
		lineageTag: 475d228e-d6b9-4096-b4ea-3c58e3aeccc2
		summarizeBy: sum
		sourceColumn: media_diaria_os_aprovador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tempo Estimado Aprovação' =
			
			7.48 * FactAprovacao[peso_os]
		lineageTag: a5d44c57-69f5-4c0d-8728-fc485d4e2ccc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsExternalApproval
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 20d2eae8-1fee-410e-8dae-e6a384889737
		summarizeBy: none
		sourceColumn: IsExternalApproval

		annotation SummarizationSetBy = Automatic

	column CustomerId
		dataType: string
		lineageTag: c4a3dd12-4b2e-42a6-8022-ac46c6d93d6c
		summarizeBy: none
		sourceColumn: CustomerId

		annotation SummarizationSetBy = Automatic

	column 'dim_metas.SLA (h)'
		dataType: double
		lineageTag: d8ef1ef6-a8dc-4b0c-a8b3-cb58bf5699b7
		summarizeBy: sum
		sourceColumn: dim_metas.SLA (h)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dentro SLA'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cefbba8c-47d7-41fa-8024-0cb1a10c6562
		summarizeBy: none
		sourceColumn: Dentro SLA

		annotation SummarizationSetBy = Automatic

	column total_aprovado_referencial
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: d7cfc0d4-939e-4f1d-93e5-8276f13447d8
		summarizeBy: sum
		sourceColumn: total_aprovado_referencial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column total_aprovado_aderente
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 4e775076-3d32-4b44-a32d-1f32a3fdba73
		summarizeBy: sum
		sourceColumn: total_aprovado_aderente

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column OS_Aprovada
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5765517b-fb73-4b5d-a621-2894a710cad1
		summarizeBy: none
		sourceColumn: OS_Aprovada

		annotation SummarizationSetBy = Automatic

	column preco_parceiro
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fb606c28-b09c-42d5-8b14-474015939419
		summarizeBy: none
		sourceColumn: preco_parceiro

		annotation SummarizationSetBy = Automatic

	partition FactAprovacao = m
		mode: import
		source =
				let
				    Fonte = Azure("SELECT * FROM hive_metastore.dev_lucas_malessa.vw_fact_aprovacao"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"OrderServiceCode", type text}, {"valor_orcado", Currency.Type}, {"_valor_aprovado", Currency.Type}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado",".",",",Replacer.ReplaceText,{"sla_aprovocao"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído",{{"sla_aprovocao", type number}}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Tipo Alterado1","Lgodinho","Legodinho",Replacer.ReplaceText,{"_aprovador"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Valor Substituído1",{{"CustomerId", type text}}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Tipo Alterado2",null,0,Replacer.ReplaceValue,{"sla_aprovocao"}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Valor Substituído2", {"CustomerId"}, dim_metas, {"Cód. Cliente"}, "dim_metas", JoinKind.LeftOuter),
				    #"dim_metas Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "dim_metas", {"SLA (h)"}, {"dim_metas.SLA (h)"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"dim_metas Expandido",null,4,Replacer.ReplaceValue,{"dim_metas.SLA (h)"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Valor Substituído3", "Personalizar", each if [sla_aprovocao] <= [#"dim_metas.SLA (h)"] then true else false),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Personalizar", type logical}, {"total_aprovado_referencial", Currency.Type}, {"total_aprovado_aderente", Currency.Type}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado3",{{"Personalizar", "Dentro SLA"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

